name: base
channels:
  - conda-forge
dependencies:
- nbconvert=6
# Python Kernel
- ipykernel=5.1
- xeus-python=0.9
- ipywidgets=7.6
- widgetsnbextension=3.5
- ipyleaflet=0.13
- pythonocc-core
- ifcopenshell
- shapely
- ipycanvas
- lxml
- sidecar
- ipycytoscape
- networkx
- nbgitpuller
- altair=4.1
- dask=2020.12
- python=3.7
- seaborn=0.11
- sympy=1.4
- pyyaml
- traittypes==0.2.1
- invoke=1.2
- rdflib
- sparqlwrapper
- pydotplus
- fastapi
- python-multipart
- pip
- uvicorn